image: ghcr.io/astral-sh/uv:0.12.21-python3.14-trixie

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH == "moonshine"'

test:
  script: [scripts/ci.sh test]

lint:
  script: [scripts/ci.sh lint]

typecheck:
  script: [scripts/ci.sh typecheck]

docs:
  image:
    name: ghcr.io/typst/typst:0.15.1
    entrypoint: [""]
  script: [scripts/ci.sh docs]
  artifacts:
    name: iyzee-documentation
    paths: [build/docs/*.pdf]
    expire_in: 30 days
