image: ghcr.io/astral-sh/uv:0.12.19-python3.14-trixie

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH == "moonshine"'

stages:
  - test
  - lint
  - typecheck
  - docs
  - maintenance

test:
  stage: test
  script:
    - ./ci.sh test

lint:
  stage: lint
  script:
    - ./ci.sh lint

typecheck:
  stage: typecheck
  script:
    - ./ci.sh typecheck

docs:
  stage: docs
  image:
    name: ghcr.io/typst/typst:0.15.1
    entrypoint: [""]
  script:
    - ./ci.sh docs
  artifacts:
    name: iyzee-documentation
    paths:
      - build/docs/*.pdf
    expire_in: 30 days

update:
  stage: maintenance
  needs: []
  when: manual
  script:
    - ./ci.sh update
    - ./ci.sh test
    - ./ci.sh lint
    - ./ci.sh typecheck
  artifacts:
    name: iyzee-update
    paths:
      - uv.lock
    expire_in: 7 days
