[project]
name = "iyzee"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ↄǝsƃ", email = "ʇǝu˙oǝʇsod@ınƃ" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "pyvisa>=1.16.2",
    "pyvisa-py>=0.8.1",
    "tabulate>=0.10.0",
]

[project.optional-dependencies]
test = [
    "pytest>=9.1.1",
]

[project.scripts]
iyzee = "iyzee.main:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"

[tool.ruff]
target-version = "py314"
line-length = 100

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I"]

[tool.mypy]
python_version = "3.14"
ignore_missing_imports = true
