[project]
name = "iyzee"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ↄǝsƃ", email = "ʇǝu˙oǝʇsod@ınƃ" }
]
requires-python = ">=3.14"
dependencies = [
    "ipython>=9.17.0",
    "pip>=26.2.1",
]

[project.optional-dependencies]
test = [
    "pytest>=8.0",
]

[project.scripts]
iyzee = "iyzee:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
